services:
  - type: web
    name: graphql-backend
    env: java
    plan: free
    rootDir: backend
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: THE_CAT_API_KEY
        sync: false
